name: Build ami on aws

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  test_and_build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      DBHOST: "localhost"
      PORT: 5000
      DBUSER: ${{ secrets.DBUSER }}
      DBPASS: ${{ secrets.DBPASS }}
      DATABASE: "csye6225"
      DBPORT: 5433
      CSV_PATH: "../users.csv"

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
          POSTGRES_DB: "app_db"
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Github code checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.5"    

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CUSTOM_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CUSTOM_DEV_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create a zip folder
        run: zip -r webapp.zip . -x ".git/*" ".gitignore" ".github/*"

      - name: Packer Init
        run: packer init packer-debian.pkr.hcl || exit 1
        working-directory: packer

      - name: Validate Packer Template
        run: packer validate packer-debian.pkr.hcl || (echo "Packer template validation failed!" && exit 1)
        working-directory: packer

      - name: Build AMI
        if: success()
        run: packer build -color=false -on-error=abort -var-file=dev.auto.pkrvars.hcl packer-debian.pkr.hcl || (echo "Packer Build failed!" && exit 1)
        working-directory: packer
        env:
          PACKER_LOG: 1